### ISSUE TITLE
attachment to load balancer

### ISSUE THREAD

**Issue by devops-cloud-labs** [DhruvinSoni30/Terraform-AWS-3tier-Architecture#2]
Error: Duplicate resource "aws_lb_target_group_attachment" configuration
│
│   on alb.tf line 27:
│   27: resource "aws_lb_target_group_attachment" "attachment" {
│
│ A aws_lb_target_group_attachment resource named "attachment" was already declared at alb.tf:17,1-55. Resource names
│ must be unique per type in each module.

**Comment by DhruvinSoni30** [comment]
I have fixed this issue. Please check now.
